#include "adc12.h"

ADC_Init_t ADC_Init = {
	DISABLE_ADC, 		/* ADC_Module */
	ADC_PORT_CHANNELS_DISABLE,	 /* ADC_Ports */
	ADC_AFSEL_DISABLE,		/* ADC_PORTB */
	ADC_AFSEL_DISABLE,		/* ADC_PORTD */
	ADC_AFSEL_DISABLE,		/* ADC_PORTE */
	ADC_SET_DEN_PORTB,		/* ADC_CLEAR_DEN_PORTB */
	ADC_SET_DEN_PORTD,		/* ADC_CLEAR_DEN_PORTD */
	ADC_SET_DEN_PORTE,		/* ADC_CLEAR_DEN_PORTE */
	ADC_AMSEL_ENABLE_PORTB,		/* ADC_AMSEL_PROTB */
	ADC_AMSEL_ENABLE_PORTD,		/* ADC_AMSEL_PROTD */
	ADC_AMSEL_ENABLE_PORTE		/* ADC_AMSEL_PROTE */
};


/* Declaration of Deinit structure for ADC. Uncomment if use */

//ADC_Deinit_t ADC_Deinit = {
//	DISABLE_ADC, 		/* ADC_Module */
//	ADC_PORT_CHANNELS_DISABLE,	 /* ADC_Ports */
//	ADC_AFSEL_DISABLE,		/* ADC_PORTB */
//	ADC_AFSEL_DISABLE,		/* ADC_PORTD */
//	ADC_AFSEL_DISABLE,		/* ADC_PORTE */
//	ADC_SET_DEN_PORTB,		/* ADC_CLEAR_DEN_PORTB */
//	ADC_SET_DEN_PORTD,		/* ADC_CLEAR_DEN_PORTD */
//	ADC_SET_DEN_PORTE,		/* ADC_CLEAR_DEN_PORTE */
//	ADC_AMSEL_ENABLE_PORTB,		/* ADC_AMSEL_PROTB */
//	ADC_AMSEL_ENABLE_PORTD,		/* ADC_AMSEL_PROTD */
//	ADC_AMSEL_ENABLE_PORTE		/* ADC_AMSEL_PROTE */
//};